const SHOW_LOADING = 'SHOW_LOADING'
const HIDE_LOADING = 'HIDE_LOADING'

const SET_MSGTIP = 'SET_MSGTIP'
const HIDE_MSGTIP = 'HIDE_MSGTIP'

const SET_CITY = 'SET_CITY'
const SET_REGISTERSTEP = 'SET_REGISTERSTEP'


export {
	SHOW_LOADING, HIDE_LOADING,

	SET_MSGTIP, HIDE_MSGTIP,

	SET_CITY, SET_REGISTERSTEP
}